### ISSUE TITLE
Default items are not loaded on a particluar trip page

### ISSUE THREAD

**Issue by slyka85** [slyka85/PackingList#2]
When a user creates a trip, he/she is being redirected to trips/id page where details of the trips are shown. I'm trying to append the list of default items on the same page as well, so that the user can select items there and then save them.
My issue is that default items are not being displayed at trips/id and the following error is given:
GET http://localhost:3000/trips/api/default_items 404 (Not Found)

If a user goes to /items, then the list of suggested (default) items is shown.

**Comment by slyka85** [comment]
This is the script from HTML

```
        <script class="item-template" type="text/template">
        {{#default_items}}
        <ul id="sortable" class="list-unstyled">
            <li class="ui-state-default">
                <div class="checkbox">
                    <label><input type="checkbox" value="" id="item">{{item}}</label>
                 </div>
            </li>
            {{/default_items}}
        </ul>
        </script>
```

And ajax call in Js file 

```
        $.ajax({url: "api/default_items", success: function(default_items){
        var template = $('.item-template').html();
        var info = Mustache.render(template, {default_items: default_items});
        $('#checkbox').append(info);
        }});
```

**Comment by andrewfritz86** [comment]
OK, so there is a request being made somewhere to `GET http://localhost:3000/trips/api/default_items` (per the error)

If you rake routes, do you have that route?

**Comment by andrewfritz86** [comment]
I am seeing this error in my console (rails console) as well

`ActionController::RoutingError (No route matches [GET] "/trips/api/default_items"):`

So for some reason, a request is being made to that route, but the route doesn't exist. Try and find out why that request is happening.

**Comment by slyka85** [comment]
it doesn't exist, I checked routes, the html files and I don't know why I would need that route..

**Comment by andrewfritz86** [comment]
The issue actually is that in your ajax request you forgot a "/" at the beginning of the url.

**Comment by slyka85** [comment]
slgjdhejle;tledr;hrdlk !
thank you :)

**Comment by andrewfritz86** [comment]
не за что
