### ISSUE TITLE
Join tables relationships

### ISSUE THREAD

**Issue by slyka85** [slyka85/PackingList#3]
I am trying to figure out how to save a trip with items added to it.
The "trips" table is connected to "default_items" table through join table "default_trip".
In rails console I tried to create a join table instance by
DefaultTrip.create(trip_id: 2, default_item_id: 15) and it works, so if i go to http://localhost:3000/api/trips/2/ I can see the trip 2 with all details and a default_item 15.

But now I am confused as to how to do it in the app, what routes and how does it know where is what...

**Comment by andrewfritz86** [comment]
So, per your ERD, when a user creates a trip, they only persist the destination and dates. They then create a series of joins matching default items to trip ids, and custom items to trip ids. 

Essentially, when a user goes to a trip's show route (so a trip with the id of 2, for example), you want to bring in the trip information for the id 2, the default items that have the trip of id 2, and the custom items that have a trip of id of 2. Then render that all to the screen.

You can send multiple things back to the client from the server as json. You could try creating a hash in rails and sending that to the client as json.

**Comment by andrewfritz86** [comment]
render :json {tripinfo: tripinfo, custom_items: custom_items, default_items: default_items}

**Comment by slyka85** [comment]
In default_trip controller i am creating a new one, and trip_id and default_item_id returns NULL  at http://localhost:3000/api/default_trips

```
        def create
      default_trip = DefaultTrip.new(default_trip_params)
      default_trip.save
      render json: default_trip.to_json
    end
```

```
    private
      def default_trip_params
        params.permit(:trip_id, :default_item_id)
      end
```

**Comment by andrewfritz86** [comment]
OK. How were you expecting to pass those through in order to appear in params?

**Comment by slyka85** [comment]
somehow trough the trip where it has its id.. and the default items' ids?

**Comment by slyka85** [comment]
I got the trip_id to be saved into join table, but default_items do not get saved

**Comment by slyka85** [comment]
I am getting the default items from database through mustache by iterating.. but how can i pass it to rails what is exactly on my page

**Comment by andrewfritz86** [comment]
Are you here?

**Comment by slyka85** [comment]
in 3A
